version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: bov-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bov-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bovdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  db_data:
