app = "projeto-final-etu0ww"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/php-apache"]

[env]
  APACHE_DOCUMENT_ROOT = "/var/www/html/public"
  APACHE_RUN_USER = "www-data"
  APACHE_RUN_GROUP = "www-data"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false