[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[env]
  APACHE_DOCUMENT_ROOT = "/var/www/html/public"