app = "https://projeto-final-etu0ww.fly.dev"  # Substitua pelo nome do seu app no Fly.io

[http_service]
  internal_port = 80
  force_https = true  # Redireciona HTTP para HTTPS

[build]
  dockerfile = "Dockerfile"