[phases.setup]
cmds = ["apt-get update", "apt-get install -y libzip-dev zip"]

[phases.install]
cmds = ["docker-php-ext-install mysqli pdo pdo_mysql"]

[phases.build]
cmds = ["a2enmod rewrite"]

[start]
cmd = "apache2-foreground"