FROM php:8.2-apache

# Instala dependências
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install \
    mysqli \
    pdo \
    pdo_mysql \
    && docker-php-ext-enable pdo_mysql

# Configura Apache
RUN a2enmod rewrite
COPY .htaccess /var/www/html/.htaccess

# Copia a aplicação
WORKDIR /var/www/html
COPY . .

# Permissões
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
CMD ["apache2-foreground"]