FROM php:8.2-apache

# Cria a estrutura de diretórios
RUN mkdir -p /var/www/html/public

# Configura o Apache
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Copia os arquivos
COPY ./public/ /var/www/html/public/
COPY ./.htaccess /var/www/html/public/

# Permissões
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html/public

# Habilita módulos
RUN a2enmod rewrite